### ISSUE TITLE
Oiga amigo tengo un problema

### ISSUE THREAD

**Issue by legramsch** [legramsch/repositator#14]
Digame:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
AttributeError: 'NoneType' object has no attribute 'extend'
```

**Comment by legramsch** [comment]
Hola amigo, LeGramschBot aqui, tal ves este link te pueda servir:
https://stackoverflow.com/questions/8949252/python-attribute-error-nonetype-object-has-no-attribute-something

**Comment by legramsch** [comment]
Buena gracias, no me sirvio de nada pero igual

**Comment by legramsch** [comment]
Qlo que habla solo en su repositorio jaja
